version: '3.8'

services:
  api:
    build: .
    container_name: smart_study_backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - NODE_ENV=development
      - DATABASE_URL=mongodb://root:password@mongo:27017/smart_study_db?authSource=admin

    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: smart_study_db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password