version: '3.8'

services:
  api:
    build: .
    container_name: smart_study_backend
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - DB_URL=${DB_URL}
      - JWT_KEY=${JWT_KEY}