version: "3.8"

services:
  api:
    build: .
    container_name: smart_study_backend
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - DB_URL=${DB_URL}
      - JWT_KEY=${JWT_KEY}
      - FRONTEND_URL=${FRONTEND_URL}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: smart_study_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
